### ISSUE TITLE
Sensor `Last Measure Value` not show at `Energy -> Solar Panels Sensor` dropdown 

### ISSUE THREAD

**Issue by alissonrubim** [fsaris/home-assistant-zonneplan-one#11]
Hi, at the Energy configuration, at Home Assistant, I can configure the the Solar Panel sensors. The problem is that, right now, only the yield_today and yield_total are available as a Long Term sensor.
So, only with this two data, HA is not capable to give me a nice chart and overview of my Energy integration.

Has some documentation from HA explaining how to fix that in the sensor:
https://www.home-assistant.io/more-info/statistics/
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Here a print screen of the configuration and you can see that the ZonnePlan integration does not show the current power generated.
[Screenshot](https://ibb.co/hd6m7mj)

**Comment by alissonrubim** [comment]
Sorry, I didn't saw that already had a issue for that at https://github.com/fsaris/home-assistant-zonneplan-one/issues/8

**Comment by fsaris** [comment]
`Zonneplan yield total` is what you’re panels produced
`Zonneplan P1 electricity consumption today` is what you used from the grid

What's missing is the energy you delivered back to the grid. For that you can configure a `integration` sensor.
See https://github.com/fsaris/home-assistant-zonneplan-one#have-production-available-for-ha-energy-dashboard

This should al be available since version https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.4

**Comment by fsaris** [comment]
Updated the readme
