### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'append'

### ISSUE THREAD

**Issue by Doemas** [fsaris/home-assistant-zonneplan-one#12]
Found this error message in my logs after installing the Zonneplan component. After configuring the integration and verifying my email address no Zonneplan entities are added to my home assistant. Tried uninstalling and reinstalling multiple times, same error.

```
Logger: custom_components.zonneplan_one.coordinator
Source: custom_components/zonneplan_one/coordinator.py:54
Integration: Zonneplan ONE (documentation, issues)
First occurred: 2 oktober 2021 21:56:29 (1 occurrences)
Last logged: 2 oktober 2021 21:56:29

Unexpected error fetching zonneplan_one data: 'dict' object has no attribute 'append'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/zonneplan_one/coordinator.py", line 54, in _async_update_data
    result[connection["uuid"]][contract["type"]].append(contract)
AttributeError: 'dict' object has no attribute 'append'
```

**Comment by fsaris** [comment]
Could you enable debug logging and share the logs?

https://github.com/fsaris/home-assistant-zonneplan-one#troubleshooting

**Comment by dstollie** [comment]
After removing some jingling with the electricity and gas contracts in our database we resolved to above issue but. This has something todo with the contract types "gas" and "electricity". @Doemas can you share you payload with the gas and electricity contract info anonymized in this ticket.

After jingling with the requests we succesfully passed the above error but we stubled apon a new error:

![Schermafbeelding 2021-10-05 om 19 14 19](https://user-images.githubusercontent.com/7110155/136071126-5003056a-72ba-4974-9e41-279954c09809.png)

I think the reason behind this, is because @Doemas is using a newer monitoring device which the API currently does not sent the firmware information. The payload which is causing the issue is probably, spefically the firmware version.

```json
'contracts': [
    {
      'meta': {
        'sunrise': None,
        'sunset': None,
        'network': {
          'name': 'Onbekend',
          'status': 'Onbekend',
          'color': 'unknown'
        },
        'sgn_serial_number': None,
        'module_firmware_version': None,
        'inverter_firmware_version': None,
        'show_in_contract_screen': False,
        'enable_pv_analysis': False
      }
    },
```

In file `sensor.py r.192` the ConnectionValue is returning a NoneType which is not compatible with the '+' operator. the ConnectionValue should either always return something compatible with the "+" operator or it should be handled properly when handling the result of `getConnectionValue`

**Comment by Doemas** [comment]
After @dstollie helped me out last night I can now see that the Zonneplan entities are added to my installation and seem to be working. The AttributeError still occurs in my logs though. I atttached my logs here.
[HALogs.log](https://github.com/fsaris/home-assistant-zonneplan-one/files/7295967/HALogs.log)

**Comment by fsaris** [comment]
> Could not find pv_installation of pv_installation
> Could not find p1_installation of p1_installation

This is probably because your second connection doesn't have a pv and p1 contract.

Are your sensors still  "not available"? Can be that the integration sensor needs some time to be restored after a restart of HA

**Comment by Doemas** [comment]
The integration sensor is available now and the energy dashboard is working fine. Thanks for your help!
