### ISSUE TITLE
Possible to add extra sensor "CheapestTime"

### ISSUE THREAD

**Issue by dennisbrouwer91** [fsaris/home-assistant-zonneplan-one#74]
Hi,

Would it be possible to add a new sensor to Home-Assistant with the time of day where the prices are the cheapest?
Maybe zonneplan_cheapeast_today: "14:00" ? 

Dennis

**Comment by PeterKawa** [comment]
You mean this sensor I guess?
sensor.zonneplan_energie_lowest_hour_this_day
In the screenshot it says 13, so that day the cheapest time was @ 1300h / 1 PM:
![Screenshot from 2023-08-24 20-32-21](https://github.com/fsaris/home-assistant-zonneplan-one/assets/74005072/b2706f21-74b8-491b-bb46-633806d3f15e)

**Comment by dennisbrouwer91** [comment]
I suddenly understand why that is not working on my side, my contract at Zonneplan starts coming Monday, the sensor is now `unavailable`. I will check on Monday.
Also : It might be handy to change the sensor from an integer to an actual time?

**Comment by fsaris** [comment]
if you need a different representation of the value there are template options in HA to create this.

Closing this because value is present as mentioned by @PeterKawa
