### ISSUE TITLE
New costs sensors have wrong state_class

### ISSUE THREAD

**Issue by hmmbob** [fsaris/home-assistant-zonneplan-one#90]
Running 0.0.22

```
Entity sensor.electricity_delivery_costs_today (<class 'custom_components.zonneplan_one.sensor.ZonneplanP1Sensor'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/fsaris/home-assistant-zonneplan-one/issues
Entity sensor.electricity_production_costs_today (<class 'custom_components.zonneplan_one.sensor.ZonneplanP1Sensor'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/fsaris/home-assistant-zonneplan-one/issues
Entity sensor.gas_delivery_costs_today (<class 'custom_components.zonneplan_one.sensor.ZonneplanP1Sensor'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/fsaris/home-assistant-zonneplan-one/issues
```

**Comment by fsaris** [comment]
@hmmbob thanks for the feedback. Did some investigation (found for example https://github.com/home-assistant/core/issues/88457) and need to set it to `total` and set `last_reset` on the start of each day.

Looks that also to wrong value provided for `unit_of_measurement`. It should be `EUR` instead of `€`.

**Comment by fsaris** [comment]
Sensors are fixed in https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.23

Please make sure to update the existing statistics see release note

[![Open your Home Assistant instance and show your statistics developer tools.](https://my.home-assistant.io/badges/developer_statistics.svg)](https://my.home-assistant.io/redirect/developer_statistics/)

**Comment by hmmbob** [comment]
Works, thanks Frans!

**Comment by MathijsG** [comment]
What to change on my end? I can't seem to change any unit on these sensors?

![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/529552/6594818e-6a36-4b00-a096-8d50f2c6ad11)
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/529552/fc19b9ba-f090-450a-bd7d-6b5b8df70f8e)

**Comment by fsaris** [comment]
Seems you don't have the sensors enabled so no need to update anything
